# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6de5c102553c6c18debc32fb4d9ff8d7fba98dbb8a822cd2875e0a455229536216d7b746ec1a31ba7acc409f9f6046fb864757ae6ee81d0470c754ea22daae9

test:
  secret_key_base: b60b54c225658624b4a7c581c92cc188f2cb3541c12d10fbb5d4e6e2dacdfc9089212e3a7c14a1159b8a12fbd0c20c7df8289f92967e154afcf31aea3e506752

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
